services:
  coordinator:
    build:
      context: ./nodes/koi-net-coordinator-node
    ports:
      - "8080:8080"
    env_file:
      - ./config/docker/global.env
    environment:
      - RUN_CONTEXT=docker
      - KOI_CONFIG_MODE=docker
      - RID_CACHE_DIR=/data/cache
    volumes:
      - ./config:/config:ro
      - cache_data:${RID_CACHE_DIR}
      - coordinator_state_data:/app/.koi/coordinator
    restart: unless-stopped
    networks:
      - koinet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/koi-net/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  github-sensor:
    build:
      context: ./nodes/koi-net-github-sensor-node
    ports:
      - "8001:8001"
    env_file:
      - ./config/docker/global.env
    environment:
      - RUN_CONTEXT=docker
      - KOI_CONFIG_MODE=docker
      - RID_CACHE_DIR=/data/cache
    volumes:
      - ./config:/config:ro
      - cache_data:${RID_CACHE_DIR}
      - github_state_data:/app/.koi/github
    depends_on:
      coordinator:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - koinet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8001/koi-net/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  hackmd-sensor:
    build:
      context: ./nodes/koi-net-hackmd-sensor-node
    ports:
      - "8002:8002"
    env_file:
      - ./config/docker/global.env
    environment:
      - RUN_CONTEXT=docker
      - KOI_CONFIG_MODE=docker
      - RID_CACHE_DIR=/data/cache
    volumes:
      - ./config:/config:ro
      - cache_data:${RID_CACHE_DIR}
      - hackmd_state_data:/app/.koi/hackmd
    depends_on:
      coordinator:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - koinet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8002/koi-net/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  processor-a:
    build:
      context: ./nodes/koi-net-processor-a-node
    ports:
      - "8011:8011"
    env_file:
      - ./config/docker/global.env
    environment:
      - RUN_CONTEXT=docker
      - KOI_CONFIG_MODE=docker
      - RID_CACHE_DIR=/data/cache
    volumes:
      - ./config:/config:ro
      - cache_data:${RID_CACHE_DIR}
      - processor_a_state:/app/.koi/processor-a
    depends_on:
      coordinator:
        condition: service_healthy
      github-sensor:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - koinet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8011/koi-net/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  processor-b:
    build:
      context: ./nodes/koi-net-processor-b-node
    ports:
      - "8012:8012"
    env_file:
      - ./config/docker/global.env
    environment:
      - RUN_CONTEXT=docker
      - KOI_CONFIG_MODE=docker
      - RID_CACHE_DIR=/data/cache
    volumes:
      - ./config:/config:ro
      - cache_data:${RID_CACHE_DIR}
      - processor_b_state:/app/.koi/processor-b
    depends_on:
      coordinator:
        condition: service_healthy
      hackmd-sensor:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - koinet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8012/koi-net/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  cache_data:
    driver: local
  coordinator_state_data:
    driver: local
  github_state_data:
    driver: local
  hackmd_state_data:
    driver: local
  processor_a_state:
    driver: local
  processor_b_state:
    driver: local

networks:
  koinet:
    driver: bridge
