services:
  - type: web
    name: koi-coordinator
    runtime: docker
    dockerfilePath: ./nodes/koi-net-coordinator-node/Dockerfile
    dockerContext: ./nodes/koi-net-coordinator-node
    envVars:
      - fromGroup: koi-env
    plan: free
    autoDeploy: false

  - type: web
    name: koi-github-sensor
    runtime: docker
    dockerfilePath: ./nodes/koi-net-github-sensor-node/Dockerfile
    dockerContext: ./nodes/koi-net-github-sensor-node
    envVars:
      - fromGroup: koi-env
    plan: free
    autoDeploy: false

  - type: web
    name: koi-hackmd-sensor
    runtime: docker
    dockerfilePath: ./nodes/koi-net-hackmd-sensor-node/Dockerfile
    dockerContext: ./nodes/koi-net-hackmd-sensor-node
    envVars:
      - fromGroup: koi-env
    plan: free
    autoDeploy: false

  - type: web
    name: koi-processor-a
    runtime: docker
    dockerfilePath: ./nodes/koi-net-processor-a-node/Dockerfile
    dockerContext: ./nodes/koi-net-processor-a-node
    envVars:
      - fromGroup: koi-env
    plan: free
    autoDeploy: false

  - type: web
    name: koi-processor-b
    runtime: docker
    dockerfilePath: ./nodes/koi-net-processor-b-node/Dockerfile
    dockerContext: ./nodes/koi-net-processor-b-node
    envVars:
      - fromGroup: koi-env
    plan: free
    autoDeploy: false

envVarGroups:
  - name: koi-env
    envVars:
      - key: GITHUB_TOKEN
        value: <github-token>
      - key: HACKMD_TOKEN
        value: <hackmd-token>
      - key: GITHUB_WEBHOOK_SECRET
        value: <github-webhook-secret>
      - key: RID_CACHE_DIR
        value: /data/cache
      - key: SUBNET_ID
        value: demo-subnet
      - key: RUN_CONTEXT
        value: docker
      - key: KOI_CONFIG_MODE
        value: docker
