app = "koi-demo-coordinator"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"
  [build.args]
    SERVICE_NAME = "coordinator"

[env]
  RUN_CONTEXT     = "docker"
  KOI_CONFIG_MODE = "docker"
  RID_CACHE_DIR   = "/data/cache"

[[mounts]]
  source      = "coordinator_state_data"
  destination = "/app/.koi/coordinator"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/koi-net/health"
    protocol = "http"