api:
  token_env_var: HACKMD_TOKEN
edges:
  coordinator_url: http://0.0.0.0:8080/koi-net
runtime:
  base_url: http://0.0.0.0:8002/koi-net
  cache_dir: ${RID_CACHE_DIR}
  state_file: ${RID_CACHE_DIR}/hackmd_state.json
  host: 0.0.0.0
  log_level: INFO
  port: 8002
sensor:
  kind: hackmd
  poll_interval: 300
  target_note_ids:
    - C1xso4C8SH-ZzDaloTq4Uw
  team_path: blockscience
