app = "koi-demo-processor-b"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  RUN_CONTEXT     = "docker"
  KOI_CONFIG_MODE = "docker"
  RID_CACHE_DIR   = "/data/cache"

[[mounts]]
  source      = "processor_b_state_data"
  destination = "/app/.koi/processor_b"

[[services]]
  internal_port = 8012
  protocol      = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port     = 80 