app = "koi-demo-gh-sensor"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"
  [build.args]
    SERVICE_NAME = "github-sensor"

[env]
  RUN_CONTEXT     = "docker"
  KOI_CONFIG_MODE = "docker"
  RID_CACHE_DIR   = "/data/cache"

[[mounts]]
  source      = "github_sensor_state_data"
  destination = "/app/.koi/github_sensor"

[[services]]
  internal_port = 8001
  protocol      = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port     = 80 