name: CI/CD → Fly.io

on:
  push:
    branches: [deploy]

jobs:
  deploy_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy coordinator
        working-directory: nodes/koi-net-coordinator-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Deploy github sensor
        working-directory: nodes/koi-net-github-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Deploy hackmd sensor
        working-directory: nodes/koi-net-hackmd-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Deploy processor a
        working-directory: nodes/koi-net-processor-a-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Deploy processor b
        working-directory: nodes/koi-net-processor-b-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
