name: CI/CD → Fly.io

on:
  push:
    branches: [deploy]

jobs:
  deploy_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Copy config and env for coordinator
        run: |
          cp config/docker/coordinator.yaml nodes/koi-net-coordinator-node/config.yaml
          cp config/docker/global.env nodes/koi-net-coordinator-node/global.env

      - name: Deploy coordinator
        working-directory: nodes/koi-net-coordinator-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Copy config and env for github sensor
        run: |
          cp config/docker/github-sensor.yaml nodes/koi-net-github-sensor-node/config.yaml
          cp config/docker/global.env nodes/koi-net-github-sensor-node/global.env

      - name: Deploy github sensor
        working-directory: nodes/koi-net-github-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Copy config and env for hackmd sensor
        run: |
          cp config/docker/hackmd-sensor.yaml nodes/koi-net-hackmd-sensor-node/config.yaml
          cp config/docker/global.env nodes/koi-net-hackmd-sensor-node/global.env

      - name: Deploy hackmd sensor
        working-directory: nodes/koi-net-hackmd-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Copy config and env for processor a
        run: |
          cp config/docker/processor-a.yaml nodes/koi-net-processor-a-node/config.yaml
          cp config/docker/global.env nodes/koi-net-processor-a-node/global.env

      - name: Deploy processor a
        working-directory: nodes/koi-net-processor-a-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Copy config and env for processor b
        run: |
          cp config/docker/processor-b.yaml nodes/koi-net-processor-b-node/config.yaml
          cp config/docker/global.env nodes/koi-net-processor-b-node/global.env

      - name: Deploy processor b
        working-directory: nodes/koi-net-processor-b-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
