name: CI/CD → Fly.io

on:
  push:
    branches: [deploy]

jobs:
  deploy_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all history is fetched
          lfs: true # Include LFS objects if you use Git LFS

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Verify config files and permissions
        run: |
          echo "Verifying config files exist:"
          ls -la config/docker/
          echo "Setting proper permissions:"
          chmod -R 755 config/docker/

      - name: Create global.env with secrets
        run: |
          echo "Creating global.env with secrets:"
          # Start with the example file as a base (for structure)
          cp config/docker/global.env.example config/docker/global.env

          # Now replace or add environment variables from GitHub secrets
          cat > config/docker/global.env << EOL
          # This file is generated during CI/CD deployment
          # Environment variables for all nodes

          # Runtime configuration
          RUN_CONTEXT=docker
          KOI_CONFIG_MODE=docker

          # Add your secrets here
          RID_CACHE_DIR=/data/cache
          GITHUB_API_TOKEN=${{ secrets.GH_API_TOKEN }}
          HACKMD_API_TOKEN=${{ secrets.HACKMD_TOKEN }}
          GITHUB_WEBHOOK_SECRET=${{ secrets.GH_WEBHOOK_SECRET }}
          EOL

          # Log that the file was created (without showing content for security)
          echo "global.env created successfully"

      - name: Prepare coordinator node
        run: |
          # Create config directory
          mkdir -p nodes/koi-net-coordinator-node/config
          # Copy config files to their expected locations
          cp config/docker/coordinator.yaml nodes/koi-net-coordinator-node/config/config.yaml
          cp config/docker/global.env nodes/koi-net-coordinator-node/config/global.env

      - name: Deploy coordinator
        working-directory: nodes/koi-net-coordinator-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Prepare github sensor node
        run: |
          # Create config directory
          mkdir -p nodes/koi-net-github-sensor-node/config
          # Copy config files to their expected locations
          cp config/docker/github-sensor.yaml nodes/koi-net-github-sensor-node/config/config.yaml
          cp config/docker/global.env nodes/koi-net-github-sensor-node/config/global.env

      - name: Deploy github sensor
        working-directory: nodes/koi-net-github-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Prepare hackmd sensor node
        run: |
          # Create config directory
          mkdir -p nodes/koi-net-hackmd-sensor-node/config
          # Copy config files to their expected locations
          cp config/docker/hackmd-sensor.yaml nodes/koi-net-hackmd-sensor-node/config/config.yaml
          cp config/docker/global.env nodes/koi-net-hackmd-sensor-node/config/global.env

      - name: Deploy hackmd sensor
        working-directory: nodes/koi-net-hackmd-sensor-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Prepare processor a node
        run: |
          # Create config directory
          mkdir -p nodes/koi-net-processor-a-node/config
          # Copy config files to their expected locations
          cp config/docker/processor-a.yaml nodes/koi-net-processor-a-node/config/config.yaml
          cp config/docker/global.env nodes/koi-net-processor-a-node/config/global.env

      - name: Deploy processor a
        working-directory: nodes/koi-net-processor-a-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Prepare processor b node
        run: |
          # Create config directory
          mkdir -p nodes/koi-net-processor-b-node/config
          # Copy config files to their expected locations
          cp config/docker/processor-b.yaml nodes/koi-net-processor-b-node/config/config.yaml
          cp config/docker/global.env nodes/koi-net-processor-b-node/config/global.env

      - name: Deploy processor b
        working-directory: nodes/koi-net-processor-b-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
